// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1MLeyrrykOj52DTpXVSahqIEDK-apYnE',
    appId: '1:718837505864:web:bf787bea652bf483a1dd7d',
    messagingSenderId: '718837505864',
    projectId: 'social-app-73092',
    authDomain: 'social-app-73092.firebaseapp.com',
    storageBucket: 'social-app-73092.appspot.com',
    measurementId: 'G-KV87X80YZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwVquC9n6WlX6MCKxOC7WiAG__DtVkrY4',
    appId: '1:718837505864:android:0df47acf4332f368a1dd7d',
    messagingSenderId: '718837505864',
    projectId: 'social-app-73092',
    storageBucket: 'social-app-73092.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV64RSYHfNbV6jRD8O3faRbqpheMZ8BAs',
    appId: '1:718837505864:ios:26993983ea701ce5a1dd7d',
    messagingSenderId: '718837505864',
    projectId: 'social-app-73092',
    storageBucket: 'social-app-73092.appspot.com',
    iosClientId: '718837505864-v5g4dmt8dobnrr8ic76nvlohn1i7a10p.apps.googleusercontent.com',
    iosBundleId: 'com.example.firbaseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV64RSYHfNbV6jRD8O3faRbqpheMZ8BAs',
    appId: '1:718837505864:ios:60f33853d39be4f7a1dd7d',
    messagingSenderId: '718837505864',
    projectId: 'social-app-73092',
    storageBucket: 'social-app-73092.appspot.com',
    iosClientId: '718837505864-hmbbaei1qe03a9otbe46fr257e6i87mo.apps.googleusercontent.com',
    iosBundleId: 'com.example.firbaseapp.RunnerTests',
  );
}
